-replace : The term '-replace' is not recognized as the name of a cmdlet, function, s
cript file, or operable program. Check the spelling of the name, or if a path was inc
luded, verify that the path is correct and try again.
At line:1 char:3
+   -replace true true
+   ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-replace:String) [], CommandNotFoundE 
   xception
    + FullyQualifiedErrorId : CommandNotFoundException
 
